services:
  - type: web
    name: your-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn todo_project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
